### PR TITLE
QGIS3 API change - Qgis.Warning

### PR DESCRIPTION
**Pull request by tomchadwin**

### CODE REVIEW

**Comment by tomchadwin** [comment]
I thought this was working, but not yet - will investigate and hopefully push a fix.

**Comment by tomchadwin** [comment]
OK, working now. I don't know how you maintain QGIS2 compatibility, so this PR is probably not appropriate, but at least it gives you the QGIS3 fix.

**Comment by mnboos** [comment]
Thanks for the PR! I will have to make small changes and will then merge it.

**Comment by mnboos** [comment]
Done: 0fe616b0fbd821afbbb808dbf74e26bbd56eef1c

**Pull request closed without merging**
