### PR TITLE
improved selection of default open directory

### PR DESCRIPTION
**Pull request by mnboos**

### CODE REVIEW

**Comment by mnboos** [comment]
@jachym Is that okay for you?

**Comment by tomchadwin** [comment]
I know you both discussed and initially disagreed on this, but I'd expect the initial folder to be the user's home folder, and for the plugin to remember the last selected folder after that (does it already do the latter?)

**Comment by mnboos** [comment]
The last selected folder is remembered during the "session", i.e. until the next qgis start. Would it be better to store the path and reload again, when qgis is started the next time?

**Comment by tomchadwin** [comment]
I'd store it in a `QSettings` so it is retained across sessions.

**Comment by mnboos** [comment]
Okay, makes probably more sense than the current implementation. On the other hand, it doesn't fit for users like @jachym, who'd like to start qgis in a specific directory.

**Comment by tomchadwin** [comment]
OK, but I'd airways go with the majority of users and what will suit them/what they are familiar with. I'd argue that the behaviour I describe is what the majority of applications do, and I'm not convinced the arguments against are strong enough to behave atypically.

**Pull request merged**
